[[towers]]
id = "archer"
name = "Archer Tower"
sprite_path = "Decorations/Buildings/Blue Buildings/Archery.png"
cost = 50
range = 256.0
damage = 25.0
fire_rate = 0.5
projectile_sprite = "Units/Blue Units/Archer/Arrow.png"
projectile_speed = 300.0
description = "Fast-firing tower that shoots arrows at enemies"

[[towers]]
id = "catapult"
name = "Catapult Tower"
sprite_path = "Decorations/Buildings/Blue Buildings/Barracks.png"
cost = 100
range = 384.0
damage = 60.0
fire_rate = 1.5
projectile_sprite = "Decorations/Rocks/Rock1.png"
projectile_speed = 200.0
description = "Slow but powerful tower that hurls rocks at enemies"

[[towers]]
id = "tower_3"
name = "New Tower 3"
sprite_path = "Decorations/Buildings/Blue Buildings/Tower.png"
cost = 10
range = 256.0
damage = 25.0
fire_rate = 5.0
projectile_sprite = "Units/Blue Units/Archer/Arrow.png"
projectile_speed = 300.0
description = "A new tower"
