[[towers]]
id = "archer"
name = "Archer"
sprite_path = "Decorations/Buildings/Blue Buildings/Archery.png"
cost = 50
range = 256.0
damage = 25.0
fire_rate = 0.5
projectile_sprite = "Units/Blue Units/Archer/Arrow.png"
projectile_speed = 300.0
description = "Fast-firing tower that shoots arrows at enemies"

[[towers]]
id = "catapult"
name = "Catapult"
sprite_path = "Decorations/Buildings/Blue Buildings/Barracks.png"
cost = 100
range = 384.0
damage = 60.0
fire_rate = 1.5
projectile_sprite = "Decorations/Rocks/Rock2.png"
projectile_speed = 200.0
description = "Slow but powerful tower that hurls rocks at enemies"

[[towers]]
id = "holy"
name = "Holy"
sprite_path = "Decorations/Buildings/Blue Buildings/Monastery.png"
cost = 300
range = 256.0
damage = 25.0
fire_rate = 5.0
projectile_sprite = "Units/Blue Units/Archer/Arrow.png"
projectile_speed = 300.0
description = "A holy tower, very effective vs. demons!"

[[towers]]
id = "tower_4"
name = "House"
sprite_path = "Decorations/Buildings/Blue Buildings/House1.png"
cost = 50
range = 256.0
damage = 25.0
fire_rate = 0.5
projectile_sprite = "Units/Blue Units/Archer/Arrow.png"
projectile_speed = 300.0
description = "A new tower"

[[towers]]
id = "cannon"
name = "Cannon"
sprite_path = "Decorations/Buildings/Blue Buildings/Test/Canon.png"
cost = 500
range = 256.0
damage = 25.0
fire_rate = 0.20000000298023224
projectile_sprite = "Units/Blue Units/Archer/Arrow.png"
projectile_speed = 300.0
description = "A massiv cannon tower"

[[towers]]
id = "dragon"
name = "Dragon"
sprite_path = "Decorations/Buildings/Blue Buildings/Test/Dragon.png"
cost = 1000
range = 256.0
damage = 100.0
fire_rate = 0.5
projectile_sprite = " Units/Fireball.png"
projectile_speed = 300.0
description = "Summons Dragons"

[[towers]]
id = "tesla"
name = "Tesla"
sprite_path = "Decorations/Buildings/Blue Buildings/Test/Tesla.png"
cost = 50
range = 256.0
damage = 25.0
fire_rate = 0.5
projectile_sprite = "Units/Blue Units/Archer/Arrow.png"
projectile_speed = 300.0
description = "A tesla tower dealing AOE damage"

[[towers]]
id = "hightower"
name = "Hightower"
sprite_path = "Decorations/Buildings/Blue Buildings/Test/High Tower.png"
cost = 150
range = 512.0
damage = 25.0
fire_rate = 0.5
projectile_sprite = "Units/Blue Units/Archer/Arrow.png"
projectile_speed = 300.0
description = "A long range tower"
