[[waves]]
wave_number = 1
spawn_interval = 2.0

[[waves.spawns]]
unit_id = "ogre"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "bear"
count = 5
health_multiplier = 1.0

[[waves]]
wave_number = 2
spawn_interval = 1.7999999523162842

[[waves.spawns]]
unit_id = "skull"
count = 1
health_multiplier = 1.2000000476837158

[[waves.spawns]]
unit_id = "goblin_lancer"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "thief"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "shaman"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "paddle_fish"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "harpoon_fish"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "turtle"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "minotaur"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "panda"
count = 1
health_multiplier = 1.0

[[waves.spawns]]
unit_id = "spider"
count = 1
health_multiplier = 1.0

[[waves]]
wave_number = 3
spawn_interval = 1.5

[[waves.spawns]]
unit_id = "warrior"
count = 5
health_multiplier = 1.5

[[waves.spawns]]
unit_id = "archer"
count = 3
health_multiplier = 1.0

[[waves]]
wave_number = 4
spawn_interval = 1.5

[[waves.spawns]]
unit_id = "warrior"
count = 10
health_multiplier = 1.7999999523162842

[[waves.spawns]]
unit_id = "lancer"
count = 2
health_multiplier = 1.0

[[waves]]
wave_number = 5
spawn_interval = 0.5

[[waves.spawns]]
unit_id = "warrior"
count = 500
health_multiplier = 1.0

[[waves]]
wave_number = 6
spawn_interval = 0.10000000149011612

[[waves.spawns]]
unit_id = "warrior"
count = 5500
health_multiplier = 1.0
